updates to imaging schema based on conversations with adam
AllenNeuralDynamics/data_schema pull request #65
Opened 2022-10-21 17:39 UTC by saskiad

Ongoing WIP on imaging schemas

2022-10-21 21:30 UTC, dyf requested changes

2022-10-21 21:30 UTC, dyf commented on schemas/imaging/acquisition.json
> +				"Inferior_to_superior",
underscores

2022-10-21 21:30 UTC, dyf commented on schemas/imaging/acquisition.json
> +				"Inferior_to_superior",
underscores

2022-10-21 21:30 UTC, dyf commented on schemas/imaging/acquisition.json
> +				"Inferior_to_superior",
underscores

2022-10-21 21:30 UTC, dyf commented on schemas/imaging/acquisition.json
> +		"local_storage_directory": {
I'm not opposed to keeping these directories here, but we will be moving data around and it will be hard to keep this straight.

2022-10-21 21:30 UTC, dyf commented on schemas/imaging/acquisition.json
> +		"x_axis": {
to do this unambiguously you also have to indicate "which dimension is x/y/z".   So, some sort of x=0, y=1, z=2 or something.

2022-10-21 22:58 UTC, saskiad commented
@camilolaiton @adamkglaser 
I made an array for the axes that combines a variety of other features - eg. Camilo had asked for reference and voxel size and these are now the dimension and voxel size within this array. Can you both take a look at this and let me know if this will work for your purposes?

2022-10-22 03:15 UTC, dyf approved these changes

2022-10-24 15:57 UTC, adamkglaser commented on schemas/imaging/acquisition.json
> +        "lasers": {
Should we make this "active lasers" or even "channels"?

2022-10-24 16:13 UTC, camilolaiton approved these changes
For the stitching pipeline, it looks great

2022-10-24 16:16 UTC, merged